# Generated by Django 3.0 on 2020-04-25 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='empty', max_length=200)),
                ('descipt_A', models.TextField(default='question a')),
                ('descipt_B', models.TextField(default='question b')),
                ('descipt_C', models.TextField(default='question c')),
                ('descipt_D', models.TextField(default='question d')),
                ('answer', models.CharField(choices=[('A', 'answer a'), ('B', 'answer b'), ('C', 'answer c'), ('D', 'answer d')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Question')),
            ],
            options={
                'unique_together': {('question_id', 'exam_id')},
            },
        ),
    ]
