# Generated by Django 3.0 on 2020-05-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='content of question')),
                ('answer_a', models.TextField(default='answer A for questions ')),
                ('answer_b', models.TextField(default='answer B for questions ')),
                ('answer_c', models.TextField(default='answer C for questions ')),
                ('answer_d', models.TextField(default='answer D for questions ')),
                ('result', models.CharField(choices=[('a', 'answer is a'), ('b', 'answer is b'), ('c', 'answer is c'), ('d', 'answer is d')], default='a', max_length=1)),
            ],
        ),
    ]
