# Generated by Django 3.0.7 on 2020-06-27 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20200627_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='grade_student', to='classroom.Grade'),
        ),
    ]
