# Generated by Django 3.0.7 on 2020-06-27 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20200418_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1)),
                ('color', models.CharField(default='#007bff', max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='grade',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='classroom.Grade'),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='grade_student', to='classroom.Grade'),
        ),
    ]
