# Generated by Django 3.0.7 on 2020-06-27 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20200627_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='student',
            name='interests',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
