# Generated by Django 3.0 on 2020-04-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='unknown2504@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='pass_word',
            field=models.CharField(default='unknown2504', max_length=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_id',
            field=models.CharField(default='user_id', max_length=16, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_name',
            field=models.CharField(default='unknown2504', max_length=25),
        ),
    ]
